services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: tasktel
      POSTGRES_USER: tasktel
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - tasktel_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tasktel -d tasktel"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: unless-stopped

volumes:
  tasktel_postgres_data:
